# Generated by Django 2.0.13 on 2019-07-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta',
            name='resposta',
            field=models.BooleanField(default=False),
        ),
    ]
