# Generated by Django 2.0.13 on 2019-05-26 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=80)),
                ('assuntos', models.CharField(choices=[('ECA', 'ENTENDENDO A CONTAMINAÇÃO DOS ALIMENTOS'), ('AMA', 'AMBIENTE DE MANIPULAÇÃO E CUIDADOS COM ÁGUA'), ('MLV', 'MANUSEIO DO LIXO E CONTROLE DE VETORES E PRAGAS'), ('HIG', 'HIGIENIZAÇÃO'), ('MEV', 'MANIPULADORES E VISITANTES'), ('EDM', 'ETAPAS DA MANIPULAÇÃO'), ('DOC', 'DOCUMENTAÇÃO')], default='', max_length=3)),
                ('conteudo', models.TextField(default='')),
                ('video', models.CharField(default='', max_length=800)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aulas.Aula')),
            ],
        ),
    ]
