# Generated by Django 2.0.13 on 2019-07-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=80)),
                ('data', models.DateTimeField()),
                ('conteudo', models.TextField(default='')),
                ('video', models.CharField(default='', max_length=800)),
                ('ativo', models.BooleanField(default=True)),
                ('resumo', models.CharField(default='', max_length=1000)),
                ('capa', models.ImageField(blank=True, default=None, upload_to='images/')),
                ('idAula', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('data', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('numAulas', models.IntegerField(default=0)),
                ('descricao', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='cursoAluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula', models.IntegerField(default=0)),
            ],
        ),
    ]
