# Generated by Django 2.0.13 on 2019-07-07 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0002_auto_20190707_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunoComentario', to=settings.AUTH_USER_MODEL),
        ),
    ]
